<?php

use Illuminate\Database\Seeder;

class spk_siswa_nilaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'6',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'7',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'8',
        	'nilai'=>'100',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'9',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'10',
        	'nilai'=>'A',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'1',
        	'id_kriteria_tujuan'=>'11',
        	'nilai'=>'C',
        ]);

        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'6',
        	'nilai'=>'70',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'7',
        	'nilai'=>'70',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'8',
        	'nilai'=>'70',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'9',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'10',
        	'nilai'=>'D',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'2',
        	'id_kriteria_tujuan'=>'11',
        	'nilai'=>'C',
        ]);

        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'6',
        	'nilai'=>'70',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'7',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'8',
        	'nilai'=>'70',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'9',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'10',
        	'nilai'=>'D',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'3',
        	'id_kriteria_tujuan'=>'11',
        	'nilai'=>'D',
        ]);

        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'6',
        	'nilai'=>'80',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'7',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'8',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'9',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'10',
        	'nilai'=>'B',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'4',
        	'id_kriteria_tujuan'=>'11',
        	'nilai'=>'B',
        ]);

        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'6',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'7',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'8',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'9',
        	'nilai'=>'90',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'10',
        	'nilai'=>'A',
        ]);
        \App\Spk_Siswa_Nilai::create([
        	'id_kelas'=>'1',
        	'id_siswa_dari'=>'5',
        	'id_kriteria_tujuan'=>'11',
        	'nilai'=>'A',
        ]);
    }
}
